# Define rate limits for each endpoints.
rateLimiters:
  - key: coin-gecko
    callPerSec: 0.1
  - key: bybit
    callPerSec: 20

# Define price scanners
priceScanners:
  - type: coin-gecko
    params:
      rateLimiterKey: coin-gecko
    assetIdByCode:
      ADA: cardano
      ALGO: algorand
      APT: aptos
      ATOM: cosmos
      AVAX: avalanche-2
      BNB: binancecoin
      BTC: bitcoin
      CMDX: comdex
      DOGE: dogecoin
      DYM: dymension
      EGLD: elrond-erd-2
      ETH: ethereum
      stETH: staked-ether
      EVMOS: evmos
      GMT: stepn
      GST: green-satoshi-token
      JUNO: juno-network
      KI: genopet-ki
      LDO: lido-dao
      LUNA: terra-luna-2
      LUNC: terra-luna
      MATIC: matic-network
      MNDE: marinade
      NEAR: near
      ORCA: orca
      OSMO: osmosis
      QCK: quicksilver
      RAY: raydium
      REBUS: rebus
      ROWAN: sifchain
      SCRT: secret
      SHIB: shiba-inu
      SOL: solana
      STRD: stride
      mSOL: msol
      wSOL: wrapped-solana
      STARS: stargaze
      USDC: usd-coin
      USDT: tether
      XRP: ripple
  # - type: live-coin-watch
  #   params:
  #     endpoint: https://api.livecoinwatch.com
  #     apiKey: '{{{liveCoinWatchApiKey}}}'
  #   assetIdByCode:
  #     ADA: ADA
  #     ALGO: ALGO
  #     APT: APT
  #     ATOM: ATOM
  #     BNB: BNB
  #     BTC: BTC
  #     DOGE: DOGE
  #     EGLD: EGLD
  #     ETH: ETH
  #     EVMOS: EVMOS
  #     GLTO: GLTO
  #     GMT: GMT
  #     LDO: LDO
  #     LUNA: LUNA
  #     LUNC: LUNC
  #     MATIC: MATIC
  #     NEAR: NEAR
  #     SOL: SOL
  #     STRD: STRD
  #     XRP: XRP