# Define rate limits for each endpoints.
rateLimiters:
  - key: coin-gecko
    callPerSec: 0.1
  - key: bybit
    callPerSec: 20

# Asset Identifiers (value is defined by the nature of the platform)
assetIdByCodeByChain:
  algorand:
    ALGO: __NATIVE__
  avalanche-c:
    AVAX: __NATIVE__
  bybit:
    ADA: ADA
    ALGO: ALGO
    APT: APT
    ATOM: ATOM
    AVAX: AVAX
    BNB: BNB
    BTC: BTC
    DOGE: DOGE
    EGLD: EGLD
    ETH: ETH
    GMT: GMT
    LDO: LDO
    LUNA: LUNA
    LUNC: LUNC
    MATIC: MATIC
    NEAR: NEAR
    SHIB: SHIB
    SOL: SOL
    USDC: USDC
    USDT: USDT
    XRP: XRP
  cardano:
    ADA: __NATIVE__
  comdex:
    CMDX: __NATIVE__
  cosmos-hub:
    ATOM: __NATIVE__
  ethereum:
    ETH: __NATIVE__
    stETH: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84'
    USDC: '0xdAC17F958D2ee523a2206206994597C13D831ec7'
    USDT: '0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48'
  evmos:
    EVMOS: __NATIVE__
  juno:
    JUNO: __NATIVE__
    GLTO: juno1j0a9ymgngasfn3l5me8qpd53l5zlm9wurfdk7r65s5mg6tkxal3qpgf5se
  multiversx:
    EGLD: __NATIVE__
  osmosis:
    OSMO: __NATIVE__
  quicksilver:
    QCK: __NATIVE__
  rebus:
    REBUS: __NATIVE__
  ripple:
    XRP: __NATIVE__
  secret-network:
    SCRT: __NATIVE__
  sifchain:
    ROWAN: __NATIVE__
  solana:
    SOL: __NATIVE__
    KI: kiGenopAScF8VF31Zbtx2Hg8qA5ArGqvnVtXb83sotc
    MNDE: MNDEFzGvMt87ueuHvVU9VcTqsAP5b3fTGPsHuuPA5ey
    ORCA: orcaEKTdK7LKz57vaAYr9QeNsVEPfiu6QeMU1kektZE
    RAY: 4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R
    mSOL: mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So
    wSOL: So11111111111111111111111111111111111111112
    USDC: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
    USDT: Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB
  stargaze:
    STARS: __NATIVE__
  stride:
    STRD: __NATIVE__

# Define asset scanners
assetScanners:
  # Algorand
  - type: algorand-native
    chain: algorand
    params:
      endpoint: '{{{algorandEndpoint}}}'
  # Avalanche C-Chain
  - type: ethereum-native
    chain: avalanche-c
    params:
      endpoint: https://rpc.ankr.com/avalanche
  # bybit
  - type: bybit-spot
    chain: bybit
    params:
      rateLimiterKey: bybit
  # Cardano
  - type: cardano-native
    chain: cardano
    params:
      apiKey: '{{{cardanoBlockFrostApiKey}}}'
  # Comdex
  - type: cosmos-native
    chain: comdex
    params:
      endpoint: https://rpc.comdex.one
  # Cosmos Hub
  - type: cosmos-native
    chain: cosmos-hub
    params:
      assetCode: ATOM
      endpoint: https://cosmos-mainnet-rpc.allthatnode.com:26657
  # Ethereum
  - type: ethereum-native
    chain: ethereum
    params:
      endpoint: https://rpc.ankr.com/eth
  - type: ethereum-secondary
    chain: ethereum
    params:
      endpoint: https://rpc.ankr.com/eth
  # Evmos
  - type: cosmos-native
    chain: evmos
    params:
      endpoint: https://evmos-rpc.polkachu.com
  # Juno
  - type: cosmos-native
    chain: juno
    params:
      endpoint: https://juno-rpc.polkachu.com
  - type: cosmos-secondary
    chain: juno
    params:
      endpoint: https://juno-rpc.polkachu.com
  # Multiversx
  - type: multiversx-native
    chain: multiversx
    params:
      endpoint: https://elrond-mainnet.public.blastapi.io  # this should be gateway (a.k.a. proxy) endpoint
  # Osmosis
  - type: cosmos-native
    chain: osmosis
    params:
      endpoint: https://osmosis-rpc.quickapi.com
  # Quicksilver
  - type: cosmos-native
    chain: quicksilver
    params:
      endpoint: https://rpc.quicksilver.zone
  # Rebus
  - type: cosmos-native
    chain: rebus
    params:
      endpoint: https://api.rebuschain.com:26657
  # Ripple
  - type: ripple-native
    chain: ripple
    params:
      endpoint: wss://s1.ripple.com/
  # Secret Network
  - type: cosmos-native
    chain: secret-network
    params:
      endpoint: https://rpc.secret.express
  # Sifchain
  - type: cosmos-native
    chain: sifchain
    params:
      endpoint: https://sifchain-rpc.polkachu.com/
  # Solana
  - type: solana-native
    chain: solana
    params:
      endpoint: '{{{solanaEndpoint}}}'
  - type: solana-secondary
    chain: solana
    params:
      endpoint: '{{{solanaEndpoint}}}'
  - type: orca-whirlpool
    chain: solana
    params:
      endpoint: '{{{solanaEndpoint}}}'
  # Stargaze
  - type: cosmos-native
    chain: stargaze
    params:
      endpoint: https://rpc.stargaze-apis.com
  # Stride
  - type: cosmos-native
    chain: stride
    params:
      endpoint: https://stride.rpc.kjnodes.com

# Define price scanners
priceScanners:
  - type: coin-gecko
    params:
      rateLimiterKey: coin-gecko
    assetIdByCode:
      ADA: cardano
      ALGO: algorand
      APT: aptos
      ATOM: cosmos
      AVAX: avalanche-2
      BTC: bitcoin
      CMDX: comdex
      DOGE: dogecoin
      EGLD: elrond-erd-2
      ETH: ethereum
      stETH: staked-ether
      EVMOS: evmos
      GMT: stepn
      JUNO: juno-network
      KI: genopet-ki
      LDO: lido-dao
      LUNA: terra-luna-2
      LUNC: terra-luna
      MATIC: matic-network
      MNDE: marinade
      NEAR: near
      ORCA: orca
      OSMO: osmosis
      QCK: quicksilver
      RAY: raydium
      REBUS: rebus
      ROWAN: sifchain
      SCRT: secret
      SHIB: shiba-inu
      SOL: solana
      STRD: stride
      mSOL: msol
      wSOL: wrapped-solana
      STARS: stargaze
      USDC: usd-coin
      USDT: tether
      XRP: ripple
  - type: live-coin-watch
    params:
      endpoint: https://api.livecoinwatch.com
      apiKey: '{{{liveCoinWatchApiKey}}}'
    assetIdByCode:
      ADA: ADA
      ALGO: ALGO
      APT: APT
      ATOM: ATOM
      BNB: BNB
      BTC: BTC
      DOGE: DOGE
      EGLD: EGLD
      ETH: ETH
      EVMOS: EVMOS
      GLTO: GLTO
      GMT: GMT
      LDO: LDO
      LUNA: LUNA
      LUNC: LUNC
      MATIC: MATIC
      NEAR: NEAR
      SOL: SOL
      STRD: STRD
      XRP: XRP